/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sdp.prac2;

import org.junit.jupiter.api.Test;
import java.util.Arrays;
import java.util.*;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

}
